language: ruby

sudo: false

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: jruby-19mode
    - rvm: rbx-2

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.
  - jruby-19mode
  - rbx-2
